angular.module('extraAir',
    [
        //external
        "ngRoute",
        "angular.filter",
        "angular-jwt",
        "ngSanitize",
        "ngMaterial",
        "ngResource",
        "ui.bootstrap",
        "angular-encryption",
        "ui.bootstrap.modal"
    ]);
